---
title: "MaAsLin2"
author: "Fernando Lucas Ruiz (fernando.lucas@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document:
    toc: true
subtitle: Cirugía digestiva, endocrina y trasplante de órganos abdominales (IMIB)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r, warning=FALSE, message=FALSE}
source("Librerias.R")
source("utils.R")

tse_lp <- readRDS("../RDSs/tse_lp.RDS")

```

```{r}
df_input_data = t(assay(tse_lp)) %>% as.data.frame()
df_input_data[1:5, 1:5]
df_input_metadata = colData(tse_lp) %>% as.data.frame()
df_input_metadata[1:5, ]
```

```{r}
fit_data2 = Maaslin2(
    input_data = df_input_data, 
    input_metadata = df_input_metadata, 
    output = "demo_output", 
    fixed_effects = c("Supervivencia", "Biliary_complications", "AR", "AHT"))
```

```{r}

# Define tus archivos de datos y de salida
input_data <- df_input_data      # Tabla de abundancias (e.g., taxones)
input_metadata <- df_input_metadata # Tabla de metadatos con batch
output <- "~/Desktop/maslin/"             # Carpeta de salida de resultados

# Ejecuta MaAsLin2 para ajustar el batch
fit_data <- Maaslin2(
  input_data = input_data,
  input_metadata = input_metadata,
  output = output,
  fixed_effects = c("Batch", "AR", "Supervivencia"),
  reference = c("Batch", "RUN 1"), 
  random_effects = NULL,
  normalization = "TSS",             # Normalización opcional, depende de tus datos
  transform = "LOG",                 # Transformación opcional
  min_abundance = 0.0001,            # Filtro de abundancia mínima
  min_prevalence = 0.1               # Filtro de prevalencia mínima
)

```

```{r}

adjusted_data <- readRDS("~/Desktop/maslin/fits/residuals.rds")
metadata <- input_metadata

```

```{r}
# coldata rownames match assay colnames
all(rownames(metadata) == colnames(adjusted_data)) # our dataset
##  [1] TRUE
class(metadata) # should be data.frame or DataFrame
##  [1] "data.frame"

# rowdata rownames match assay rownames
all(rownames(pretse_LP$tax) == rownames(adjusted_data)) # our dataset
##  [1] TRUE
class(pretse_LP$tax) # should be data.frame or DataFrame
##  [1] "data.frame"

# Counts
class(pretse_LP$abundance_table) # should be a numeric matrix
##  [1] "matrix" "array"
```

```{r}
# Create a TreeSE
tse <- TreeSummarizedExperiment(
    assays =  SimpleList(counts = t(adjusted_data)),
    colData = DataFrame(metadata),
    rowData = DataFrame(pretse_LP$tax))
```

```{r}
library(phyloseq)
# Asegúrate de que assay es una matriz
otu_table_data <- otu_table(as.matrix(assay(tse)), taxa_are_rows = TRUE)

# Asegúrate de que rowData es un data.frame y conviértelo en una tax_table
tax_table_data <- tax_table(as.matrix(as.data.frame(rowData(tse))))

# Crea el objeto phyloseq
tse_phyloseq <- phyloseq(otu_table_data, tax_table_data)

sample_data(tse_phyloseq) <- sample_data(as.data.frame(colData(tse)))

library(tidyr)

# Convertir sample_data a data.frame, aplicar drop_na y reasignarlo
filtered_sample_data <- data.frame(sample_data(tse_phyloseq)) %>%
    drop_na(Batch, Supervivencia)

# Reasignar el sample_data filtrado al objeto phyloseq
sample_data(tse_phyloseq) <- sample_data(filtered_sample_data)

```

```{r, fig.width=20, fig.height=20, warning=FALSE}
dist_methods <- unlist(distanceMethodList)
# Remove them from the vector
dist_methods <- dist_methods[-(1:3)]

# Remove the user-defined distance
dist_methods = dist_methods[-which(dist_methods=="ANY")]

plist <- vector("list", length(dist_methods))
names(plist) = dist_methods
failed_methods <- c()  # Lista para almacenar los métodos que fallan

for (i in dist_methods) {
    # Intenta calcular la matriz de distancia y la ordenación con manejo de errores
    tryCatch({
        # Calcula la matriz de distancia
        iDist <- distance(tse_lp_phyloseq, method = i)
        
        # Calcula la ordenación (cambia "MDS" a "PCoA" si es necesario)
        iMDS <- ordinate(tse_lp_phyloseq, "MDS", distance = iDist)
        
        # Crear el gráfico si la ordenación es exitosa
        p <- plot_ordination(tse_lp_phyloseq, iMDS, color = "Batch", shape = "Supervivencia") +
             ggtitle(paste("MDS using distance method", i))
        
        # Guardar el gráfico en la lista
        plist[[i]] <- p
    }, error = function(e) {
        # Si ocurre un error, añade el método a la lista de fallos
        failed_methods <<- c(failed_methods, i)
        # message(paste("Failed for distance method:", i))
    })
}


df = ldply(plist, function(x) x$data)
names(df)[1] <- "distance"
p = ggplot(df, aes(Axis.1, Axis.2, color=Batch, shape=Supervivencia))
p = p + geom_point(size=3, alpha=0.5)
p = p + facet_wrap(~distance, scales="free")
p = p + ggtitle("MDS on various distance metrics for Enterotype dataset")
p
```



