---
title: "Fer"
output: html_document
date: "2024-10-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Correcting RIN, PMI, age and sex effects

```{r}
tse_lp <- readRDS("../Documentos/Fernando/Molecular inflammation Group/metagenomic_transplant/RDSs/tse_lp.RDS")

matrix_combat <- assay(tse_lp)
covs <- colData(tse_lp)
```

```{r, eval=FALSE}
mm <- model.matrix(~ Sexo_D+Edad_D+BMI_D, data = covs)
nullmm <- model.matrix(~ 1, data = covs)

cat("Launching svaseq\n")
print(Sys.time())

dat <- as.matrix(matrix_combat)

for (i in 1:nrow(matrix_combat)) {

  for(j in 1:ncol(matrix_combat)){

     if (matrix_combat[i,j]<=0) matrix_combat[i,j]<-0

     j=j+1
  }
  i=i+1
}

# Filtrar filas con varianza mayor a cero
matrix_combat_filtered <- matrix_combat[apply(matrix_combat, 1, var) > 0, ]

svas  <- sva::svaseq(dat=as.matrix(matrix_combat_filtered), mod=mm, mod0=nullmm)
colnames(svas$sv) <- paste0("SV", seq(1:ncol(svas$sv)))
print(Sys.time())
```


```{r,eval=FALSE}
saveRDS(svas, paste0(path, "data_preprocessed/ROSMAP/ROSMAP_RINPMIAGESEX_svas.rds"))
```


```{r}
numeric.covs <- covs[,c("Supervivencia", "Biliary_complications", "AR", "AHT")]
linp <- matrix(ncol=svas$n.sv,nrow=ncol(numeric.covs))
rownames(linp) <- colnames(numeric.covs)
colnames(linp) <- paste0("SV",1:svas$n.sv)
linp[] <- 0

for(cov in 1:ncol(numeric.covs)){

  for(sva in 1:svas$n.sv){

    if(svas$n.sv == 1)
      axis <- svas$sv

    else
      axis <- svas$sv[,sva]

    linp[cov,sva] <- cor.test(as.numeric(numeric.covs[,cov]),axis)$p.value
  }
}

smallest = -10
linp10 <- log10(linp)
linp10 <- replace(linp10, linp10 <= smallest, smallest)
tonote <- signif(linp, 1)

gplots::heatmap.2(linp10, Colv = F, Rowv = F, dendrogram = "none",
          trace = "none", symbreaks = F, symkey = F, breaks = seq(-20, 0, length.out = 100),
          key = T, colsep = NULL, rowsep = NULL, sepcolor = "black",
          sepwidth = c(0.05, 0.05), main = "Corr. of SVs and covs.",
          labCol = colnames(linp10),
          labRow = colnames(numeric.covs),
          xlab = "Surrogate variables")
```

```{r}
# We remove the SVs that are significantly associated with some covariate of interest.
linpDF <- as.data.frame(linp)
svsToRemove <- sort(unique(as.vector(unlist(apply(linp,1, function(x) which(x<0.05))))))
svas$sv <- svas$sv[, -svsToRemove]
```


```{r}
covs.rs <- as.data.frame(covs[,c("Sexo_D", "Edad_D", "BMI_D")])
cat("Creating residuals taking into account", paste0(colnames(svas$sv), collapse=", "), "\n")
resids <- apply(matrix_combat, 1, function(y){
  lm( y ~ . , data=cbind(covs.rs,svas$sv))$residuals
})
rownames(resids) <- colnames(matrix_combat)
resids[1:5, 1:5]
```

```{r, echo=FALSE, eval=FALSE}
saveRDS(resids, paste0(path, "/data_preprocessed/ROSMAP/ROSMAP_RINPMIAGESEX_resids.rds"))
saveRDS(covs, paste0(path, "/data_preprocessed/ROSMAP/ROSMAP_RINPMIAGESEX_covs.rds"))
```


```{r}
pcres = prince(as.matrix(CoExpNets::trasposeDataFrame(resids,F)),covs.rs,top=20)
CoExpNets::princePlot(prince=pcres, main="ROS/MAP: residual cor. with pmi, rin, age_death and msex")
```