---
title: "Buscar mejor bajada de efecto de batch"
author: "Fernando Lucas Ruiz (fernando.lucas@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document:
    toc: true
subtitle: Cirugía digestiva, endocrina y trasplante de órganos abdominales (IMIB)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r, message=FALSE}
load("../Rdatas/lectura_conteos.RData")
load("../Rdatas/covariables_limpieza.RData")
source("Librerias.R")
source("utils.R")
```

# Preparar datos

```{r}
# vamos a colapsar las columnas de taxonomia para mia
taxonomia_combinada <- todas_muestras %>%
    unite("Combined", Phylum:Species, sep = "_", remove = F)

# buscamos los unique para ponerle IDs aleatorios
taxonos <- unique(taxonomia_combinada$Combined)
set.seed(123)  # Para reproducibilidad
random_ids <- replicate(length(taxonos), paste(sample(c(letters, 0:9), 8, replace = TRUE), collapse = ""))

taxonos_ids <- data.frame(cbind(taxonos, random_ids))

# juntar taxonos_ids a todas_muestras 
todas_muestras_taxonomia <- dplyr::left_join(taxonomia_combinada, taxonos_ids, by = c("Combined" = "taxonos"))
```

## T1

```{r}
# Crear tabla de abundancia según MIA
## voy a sumar aquellos counts que tengan random_ids y codigo iguales ya que provienen de los "slash calls"
abundance_table_T1 <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "T1") %>%
    group_by(random_ids, codigo) %>%
    summarize(Count = sum(as.numeric(Count), na.rm = TRUE)) %>%
    ungroup() %>%
    pivot_wider(names_from = codigo, values_from = Count) %>%
    mutate_all(~replace_na(., 0))

abundance_table_T1 <- as.data.frame(abundance_table_T1)
rownames(abundance_table_T1) <- abundance_table_T1$random_ids
abundance_table_T1 <- abundance_table_T1 %>% select(-random_ids)

# Crear rowdata(tax)
tax_T1 <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "T1") %>%
    dplyr::select(Phylum:Species, random_ids) %>%
    as.data.frame()

tax_T1 <- tax_T1[!duplicated(tax_T1$random_ids), ]

rownames(tax_T1) <- tax_T1$random_ids
tax_T1 <- dplyr::select(tax_T1, -random_ids)

# Creas colData (samples). Esto incluye la metadata
samples_T1 <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "T1") %>%
    dplyr::select(codigo, nombre_muestra, tipo_muestra, Batch) %>%
    as.data.frame()

samples_T1 <- samples_T1[!duplicated(samples_T1$codigo), ]

samples_metadata_T1 <- dplyr::left_join(samples_T1, covs, by= "nombre_muestra" )

rownames(samples_metadata_T1) <- samples_metadata_T1$codigo
samples_metadata_T1 <- dplyr::select(samples_metadata_T1, -codigo)

```

```{r}
# taxa tiene que tener la taxonomia en las columnas y los samples en las filas
taxa_T1 <- data.frame(t(abundance_table_T1))

# Para sacar la lista de los batch primero hay que ordenar los samples en el samples_metadata

## Asegurarse de que ambos dataframes tengan los mismos rownames
common_rows <- intersect(rownames(taxa_T1), rownames(samples_metadata_T1))

taxa_T1 <- taxa_T1[common_rows, ]
samples_metadata_T1 <- samples_metadata_T1[match(rownames(taxa_T1), rownames(samples_metadata_T1)), ]

covar_T1 <- samples_metadata_T1 

taxa_T1 <- taxa_T1[rownames(taxa_T1) %in% rownames(covar_T1), ]

batchid_T1 <- as.factor(covar_T1$Batch)

covar_T1 <- covar_T1 %>%
    dplyr::select(-c("nombre_muestra", "Batch", "tipo_muestra"))
```

## Todas

```{r}
# Crear tabla de abundancia según MIA
## voy a sumar aquellos counts que tengan random_ids y codigo iguales ya que provienen de los "slash calls"
abundance_table <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "LP" | tipo_muestra == "T1") %>%
    group_by(random_ids, codigo) %>%
    summarize(Count = sum(as.numeric(Count), na.rm = TRUE)) %>%
    ungroup() %>%
    pivot_wider(names_from = codigo, values_from = Count) %>%
    mutate_all(~replace_na(., 0))

abundance_table <- as.data.frame(abundance_table)
rownames(abundance_table) <- abundance_table$random_ids
abundance_table <- abundance_table %>% select(-random_ids)

# Crear rowdata(tax)
tax <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "LP" | tipo_muestra == "T1") %>%
    dplyr::select(Phylum:Species, random_ids) %>%
    as.data.frame()

tax <- tax[!duplicated(tax$random_ids), ]

rownames(tax) <- tax$random_ids
tax <- dplyr::select(tax, -random_ids)

# Creas colData (samples). Esto incluye la metadata
samples <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "LP" | tipo_muestra == "T1") %>%
    dplyr::select(codigo, nombre_muestra, tipo_muestra, Batch) %>%
    as.data.frame()

samples <- samples[!duplicated(samples$codigo), ]

samples_metadata <- dplyr::left_join(samples, covs, by= "nombre_muestra" )

rownames(samples_metadata) <- samples_metadata$codigo
samples_metadata <- dplyr::select(samples_metadata, -codigo)

```

```{r}
# taxa tiene que tener la taxonomia en las columnas y los samples en las filas
taxa <- data.frame(t(abundance_table))

# Para sacar la lista de los batch primero hay que ordenar los samples en el samples_metadata

## Asegurarse de que ambos dataframes tengan los mismos rownames
common_rows <- intersect(rownames(taxa), rownames(samples_metadata))

taxa <- taxa[common_rows, ]
samples_metadata <- samples_metadata[match(rownames(taxa), rownames(samples_metadata)), ]

covar <- samples_metadata 

taxa <- taxa[rownames(taxa) %in% rownames(covar), ]

batchid <- as.factor(covar$Batch)

covar <- covar %>%
    dplyr::select(-c("nombre_muestra", "Batch"))

covariables <- covar %>%
    dplyr::select("Supervivencia", "MEAF_score", "AR", "AHT", "Biliary_complications")
```

```{r, eval=FALSE}
taxa_coregida <- ConQuR(tax_tab=taxa, 
                        batchid=batchid, 
                        covariates=covariables, 
                        batch_ref="RUN 3")

saveRDS(taxa_coregida, "../RDSs/taxa_corrected_todas_muestras.RDS")
```

```{r}
taxa_corrected_todas_muestras <- readRDS("../RDSs/taxa_corrected_todas_muestras.RDS")

par(mfrow = c(2,1))
Plot_PCoA(TAX=taxa_corrected_todas_muestras, factor=batchid, main=paste0("Variables salida", " Bray-Curtis"))
Plot_PCoA(TAX=taxa_corrected_todas_muestras, factor=batchid, dissimilarity = "Aitch", main=paste0("Variables salida", " Aitchison"))

```

# Guardar

```{r}
save.image("../Rdatas/Efecto Batch T1.RData")
```




