---
title: "Corregir batch con relative abundance"
author: "Fernando Lucas Ruiz (fernando.lucas@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document:
    toc: true
subtitle: Cirugía digestiva, endocrina y trasplante de órganos abdominales (IMIB)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r}
source("Librerias.R")
source("utils.R")
otus_lp_t1_t3 <- readRDS("../RDSs/otus_lp_t1_t3.RDS")
otus_bilis <- readRDS("../RDSs/otus_bilis.RDS")
otus_negative_controls <- readRDS("../RDSs/otus_negative_controls.RDS")
covs <- readRDS("../RDSs/covs.RDS")
```

# Preparar datos

```{r}
taxonomia_combinada_lp_t1_t3 <- otus_lp_t1_t3 %>%
    unite("Combined", Phylum:Species, sep = "_", remove = F)
taxonomia_combinada_bilis <- otus_bilis %>%
    unite("Combined", Phylum:Species, sep = "_", remove = F)
taxonomia_combinada_negative_controls <- otus_negative_controls %>%
    unite("Combined", Phylum:Species, sep = "_", remove = F)


taxonomia_combinada <- rbind(taxonomia_combinada_lp_t1_t3[,1:6], taxonomia_combinada_bilis[,1:6], taxonomia_combinada_negative_controls[,1:6]) 

taxonos <- unique(taxonomia_combinada$Combined)
set.seed(123)  # Para reproducibilidad
random_ids <- replicate(length(taxonos), {
  first_letter <- sample(letters, 1)  # Seleccionar una letra para el primer carácter
  rest <- sample(c(letters, 0:9), 15, replace = TRUE)  # Generar el resto del ID
  paste(c(first_letter, rest), collapse = "")  # Combinar la letra con el resto
})

taxonos_ids <- data.frame(cbind(taxonos, random_ids))

# juntar taxonos_ids a todas_muestras 
otus_lp_t1_t3_combined <- dplyr::left_join(taxonomia_combinada_lp_t1_t3, taxonos_ids, by = c("Combined" = "taxonos"))
otus_bilis_combined <- dplyr::left_join(taxonomia_combinada_bilis, taxonos_ids, by = c("Combined" = "taxonos"))
otus_negative_controls_combined <- dplyr::left_join(taxonomia_combinada_negative_controls, taxonos_ids, by = c("Combined" = "taxonos"))
```

```{r}
samples_LP <- otus_lp_t1_t3_combined %>%
    dplyr::filter(tipo_muestra == "LP") 

pretse_LP <- prepare_TSE_data(samples_LP, covs)
```

```{r}
# coldata rownames match assay colnames
all(rownames(pretse_LP$samples_metadata) == colnames(pretse_LP$abundance_table)) # our dataset
##  [1] TRUE
class(pretse_LP$samples_metadata) # should be data.frame or DataFrame
##  [1] "data.frame"

# rowdata rownames match assay rownames
all(rownames(pretse_LP$tax) == rownames(pretse_LP$abundance_table)) # our dataset
##  [1] TRUE
class(pretse_LP$tax) # should be data.frame or DataFrame
##  [1] "data.frame"

# Counts
class(pretse_LP$abundance_table) # should be a numeric matrix
##  [1] "matrix" "array"
```

```{r}
# Create a TreeSE
tse <- TreeSummarizedExperiment(
    assays =  SimpleList(counts = pretse_LP$abundance_table),
    colData = DataFrame(pretse_LP$samples_metadata),
    rowData = DataFrame(pretse_LP$tax))

tse <- transformAssay(tse, assay.type = "counts", method = "relabundance")
```

```{r}
# taxa tiene que tener la taxonomia en las columnas y los samples en las filas
taxa_LP <- data.frame(t(assay(tse, "relabundance")))

# Para sacar la lista de los batch primero hay que ordenar los samples en el samples_metadata

## Asegurarse de que ambos dataframes tengan los mismos rownames
common_rows <- intersect(rownames(taxa_LP), rownames(pretse_LP$samples_metadata))

taxa_LP <- taxa_LP[common_rows, ]
samples_metadata_LP <- pretse_LP$samples_metadata[match(rownames(taxa_LP), rownames(pretse_LP$samples_metadata)), ]

covar_LP <- samples_metadata_LP 

taxa_LP <- taxa_LP[rownames(taxa_LP) %in% rownames(covar_LP), ]

batchid_LP <- as.factor(covar_LP$Batch)

covar_LP <- covar_LP %>%
    dplyr::select(-c("nombre_muestra", "Batch", "tipo_muestra"))

covar_salida <- covar_LP %>% 
    dplyr::select(MEAF_score, Supervivencia, AR, AHT, Biliary_complications) 
```

### Fine tunning automático

```{r, eval=FALSE}
result_tuned <- Tune_ConQuR(tax_tab=taxa_LP,
                           batchid=batchid_LP,
                           covariates=covar_salida,
                           batch_ref_pool=c("RUN 1", "RUN 2", "RUN 3"),
                           logistic_lasso_pool=c(T, F),
                           quantile_type_pool=c("standard", "lasso"),
                           simple_match_pool=c(T, F),
                           lambda_quantile_pool=c(NA, "2p/n", "2p/logn"),
                           interplt_pool=c(T, F),
                           frequencyL=0,
                           frequencyU=1,
                           num_core = num_cores-2)

saveRDS(result_tuned, "../RDSs/result_tuned_relabundance.RDS")
```

Pruebas realizadas en el archivo "Buscar mejor bajada efecto Batch.Rmd"

```{r}
taxa_corrected_salida <- readRDS("../RDSs/result_tuned_relabundance.RDS")
par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa_LP, factor=batchid_LP, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected_salida$tax_final, factor=batchid_LP, main="ConQuR (Default), Bray-Curtis")

Plot_PCoA(TAX=taxa_LP, factor=batchid_LP, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected_salida$tax_final, factor=batchid_LP, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")
taxa_corrected_salida$tax_final %>% as.data.frame()
```

```{r,warning=FALSE}
PERMANOVA_R2(taxa_LP, batchid_LP, covar_salida)
adonis2(taxa_LP ~ pretse_LP$samples_metadata$Batch)
adonis2(taxa_LP ~ pretse_LP$samples_metadata$Supervivencia)

PERMANOVA_R2(taxa_corrected_salida$tax_final, batchid_LP, covar_salida)
adonis2(taxa_corrected_salida$tax_final ~ pretse_LP$samples_metadata$Batch)
adonis2(taxa_corrected_salida$tax_final ~ pretse_LP$samples_metadata$Supervivencia)
```

```{r}
taxa_corrected_salida <- data.frame(t(taxa_corrected_salida$tax_final))
# Quitar la "X" solo de los nombres de columnas que empiezan por "X"
colnames(taxa_corrected_salida) <- sub("^X", "", colnames(taxa_corrected_salida))

rownames(taxa_corrected_salida) <- sub("^X", "", rownames(taxa_corrected_salida))

pretse_LP$abundance_table <- as.matrix(taxa_corrected_salida)
```

```{r}
# Create a TreeSE
tse <- TreeSummarizedExperiment(
    assays =  SimpleList(counts = pretse_LP$abundance_table),
    colData = DataFrame(pretse_LP$samples_metadata),
    rowData = DataFrame(pretse_LP$tax))
```

```{r}
library(phyloseq)
# Asegúrate de que assay es una matriz
otu_table_data <- otu_table(as.matrix(assay(tse)), taxa_are_rows = TRUE)

# Asegúrate de que rowData es un data.frame y conviértelo en una tax_table
tax_table_data <- tax_table(as.matrix(as.data.frame(rowData(tse))))

# Crea el objeto phyloseq
tse_phyloseq <- phyloseq(otu_table_data, tax_table_data)

sample_data(tse_phyloseq) <- sample_data(as.data.frame(colData(tse)))

library(tidyr)

# Convertir sample_data a data.frame, aplicar drop_na y reasignarlo
filtered_sample_data <- data.frame(sample_data(tse_phyloseq)) %>%
    drop_na(Batch, Supervivencia)

# Reasignar el sample_data filtrado al objeto phyloseq
sample_data(tse_phyloseq) <- sample_data(filtered_sample_data)

```

```{r, fig.width=20, fig.height=20, warning=FALSE}
dist_methods <- unlist(distanceMethodList)
# Remove them from the vector
dist_methods <- dist_methods[-(1:3)]

# Remove the user-defined distance
dist_methods = dist_methods[-which(dist_methods=="ANY")]

plist <- vector("list", length(dist_methods))
names(plist) = dist_methods
failed_methods <- c()  # Lista para almacenar los métodos que fallan

for (i in dist_methods) {
    # Intenta calcular la matriz de distancia y la ordenación con manejo de errores
    tryCatch({
        # Calcula la matriz de distancia
        iDist <- distance(tse_phyloseq, method = i)
        
        # Calcula la ordenación (cambia "MDS" a "PCoA" si es necesario)
        iMDS <- ordinate(tse_phyloseq, "MDS", distance = iDist)
        
        # Crear el gráfico si la ordenación es exitosa
        p <- plot_ordination(tse_phyloseq, iMDS, color = "Batch", shape = "Supervivencia") +
             ggtitle(paste("MDS using distance method", i))
        
        # Guardar el gráfico en la lista
        plist[[i]] <- p
    }, error = function(e) {
        # Si ocurre un error, añade el método a la lista de fallos
        failed_methods <<- c(failed_methods, i)
        # message(paste("Failed for distance method:", i))
    })
}


df = plyr::ldply(plist, function(x) x$data)
names(df)[1] <- "distance"
p = ggplot(df, aes(Axis.1, Axis.2, color=Batch, shape=Supervivencia))
p = p + geom_point(size=3, alpha=0.5)
p = p + facet_wrap(~distance, scales="free")
p = p + ggtitle("MDS on various distance metrics for Enterotype dataset")
p
```