---
title: "ConQuR"
author: "Fernando Lucas Ruiz (fernando.lucas@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document:
    toc: true
subtitle: Cirugía digestiva, endocrina y trasplante de órganos abdominales (IMIB)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r}
source("Librerias.R")
```


```{r, eval=FALSE}
install.packages("doParallel")
devtools::install_github("wdl2459/ConQuR")
install.packages("coda.base")
```

# Meter datos

```{r}
# vamos a colapsar las columnas de taxonomia para mia
taxonomia_combinada <- todas_muestras %>%
    unite("Combined", Phylum:Species, sep = "_", remove = F)

# buscamos los unique para ponerle IDs aleatorios
taxonos <- unique(taxonomia_combinada$Combined)
set.seed(123)  # Para reproducibilidad
random_ids <- replicate(length(taxonos), paste(sample(c(letters, 0:9), 8, replace = TRUE), collapse = ""))

taxonos_ids <- data.frame(cbind(taxonos, random_ids))

# juntar taxonos_ids a todas_muestras 
todas_muestras_taxonomia <- dplyr::left_join(taxonomia_combinada, taxonos_ids, by = c("Combined" = "taxonos"))
```

```{r}
# Crear tabla de abundancia según MIA
## voy a sumar aquellos counts que tengan random_ids y codigo iguales ya que provienen de los "slash calls"
abundance_table <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "LP") %>%
    group_by(random_ids, codigo) %>%
    summarize(Count = sum(as.numeric(Count), na.rm = TRUE)) %>%
    ungroup() %>%
    pivot_wider(names_from = codigo, values_from = Count) %>%
    mutate_all(~replace_na(., 0))

abundance_table <- as.data.frame(abundance_table)
rownames(abundance_table) <- abundance_table$random_ids
abundance_table <- abundance_table %>% select(-random_ids)

# Crear rowdata(tax)
tax <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "LP") %>%
    dplyr::select(Phylum:Species, random_ids) %>%
    as.data.frame()

tax <- tax[!duplicated(tax$random_ids), ]

rownames(tax) <- tax$random_ids
tax <- dplyr::select(tax, -random_ids)

# Creas colData (samples). Esto incluye la metadata
samples <- todas_muestras_taxonomia %>%
    dplyr::filter(tipo_muestra == "LP") %>%
    dplyr::select(codigo, nombre_muestra, tipo_muestra, Batch) %>%
    as.data.frame()

samples <- samples[!duplicated(samples$codigo), ]

samples_metadata <- dplyr::left_join(samples, covs, by= "nombre_muestra" )

rownames(samples_metadata) <- samples_metadata$codigo
samples_metadata <- dplyr::select(samples_metadata, -codigo)

```


# LP

```{r}
# taxa tiene que tener la taxonomia en las columnas y los samples en las filas
taxa <- data.frame(t(abundance_table))

# Para sacar la lista de los batch primero hay que ordenar los samples en el samples_metadata

## Asegurarse de que ambos dataframes tengan los mismos rownames
common_rows <- intersect(rownames(taxa), rownames(samples_metadata))

taxa <- taxa[common_rows, ]
samples_metadata <- samples_metadata[match(rownames(taxa), rownames(samples_metadata)), ]

covar_lp <- samples_metadata 

taxa_lp <- taxa[rownames(taxa) %in% rownames(covar_lp), ]

batchid_lp <- as.factor(covar_lp$Batch)

covar_lp <- covar_lp %>%
    dplyr::select(-c("nombre_muestra", "Batch", "tipo_muestra"))

```

## ConQuR sin filtrado

```{r, eval=FALSE}
taxa_corrected_todas_lp <- ConQuR(tax_tab=taxa_lp, batchid=batchid_lp, covariates=covar_lp, batch_ref="RUN 46", num_core = num_cores-2)

saveRDS(taxa_corrected_todas_lp, "taxa_corrected_todas_lp.RDS")
```

```{r}
taxa_corrected_todas_lp <- readRDS("../RDSs/taxa_corrected_todas_lp.RDS")
par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected_todas_lp, factor=batchid_lp, main="ConQuR (Default), Bray-Curtis")

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected_todas_lp, factor=batchid_lp, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")
```

```{r}
permanova_taxa_todas_variables_lp <- PERMANOVA_R2(TAX=taxa_corrected_todas_lp, batchid=batchid_lp, covariates=covar_lp, key_index=2)

permanovas["LP todas variables",1] = permanova_taxa_todas_variables_lp$tab_count[1,1]
permanovas["LP todas variables",2] = permanova_taxa_todas_variables_lp$tab_count[2,1]
permanovas["LP todas variables",3] = permanova_taxa_todas_variables_lp$tab_rel[1,1]
permanovas["LP todas variables",4] = permanova_taxa_todas_variables_lp$tab_rel[2,1]

reactable::reactable(round(permanovas, 3)*100)
```

## ConQuR filtrado
### Datos donante

```{r}
# Ahora las covariables
covar_donante_lp <- covar_lp %>%
    dplyr::select(Donación, Sexo_D, Edad_D, BMI_D, GOT_D, GPT_D, PT_ACT_D, Cold_Isch, Machine_SRR, Machine_NRP, Machine_DBD, NRP_Total)
```

```{r, eval=FALSE}
taxa_corrected_donante_lp <- ConQuR(tax_tab=taxa_lp, batchid=batchid_lp, covariates=covar_donante_lp, batch_ref="RUN 46", num_core = num_cores-2)

saveRDS(taxa_corrected_donante_lp, "taxa_corrected_donante_lp.RDS")
```

```{r}
taxa_corrected_donante_lp <- readRDS("taxa_corrected_donante_lp.RDS")
par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected_donante_lp, factor=batchid_lp, main="ConQuR (Default), Bray-Curtis")

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected_donante_lp, factor=batchid_lp, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")

```

```{r}
permanova_taxa_corrected_donante_lp <- PERMANOVA_R2(TAX=taxa_corrected_donante_lp, batchid=batchid_lp, covariates=covar_donante_lp, key_index=1)

permanovas["LP variables donante",1] = permanova_taxa_corrected_donante_lp$tab_count[1,1]
permanovas["LP variables donante",2] = permanova_taxa_corrected_donante_lp$tab_count[2,1]
permanovas["LP variables donante",3] = permanova_taxa_corrected_donante_lp$tab_rel[1,1]
permanovas["LP variables donante",4] = permanova_taxa_corrected_donante_lp$tab_rel[2,1]

reactable::reactable(round(permanovas, 3)*100)
```

### Datos donante filtrado

```{r}
# Ahora las covariables
covar_donante_2_lp <- covar_lp %>%
    dplyr::select(Donación, Sexo_D, Edad_D, BMI_D)
```

```{r, eval=FALSE}
taxa_corrected_donante_2_lp <- ConQuR(tax_tab=taxa_lp, batchid=batchid_lp, covariates=covar_donante_2_lp, batch_ref="RUN 46", num_core = num_cores-2)

saveRDS(taxa_corrected_donante_2_lp, "taxa_corrected_donante_2_lp.RDS")
```

```{r}
taxa_corrected_donante_2_lp <- readRDS("taxa_corrected_donante_2_lp.RDS")
par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected_donante_2_lp, factor=batchid_lp, main="ConQuR (Default), Bray-Curtis")

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected_donante_2_lp, factor=batchid_lp, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")

```

```{r}
permanova_taxa_corrected_donante_2_lp <- PERMANOVA_R2(TAX=taxa_corrected_donante_2_lp, batchid=batchid_lp, covariates=covar_donante_2_lp, key_index=1)

permanovas["LP Donación, Sexo_D, Edad_D, BMI_D",1] = permanova_taxa_corrected_donante_2_lp$tab_count[1,1]
permanovas["LP Donación, Sexo_D, Edad_D, BMI_D",2] = permanova_taxa_corrected_donante_2_lp$tab_count[2,1]
permanovas["LP Donación, Sexo_D, Edad_D, BMI_D",3] = permanova_taxa_corrected_donante_2_lp$tab_rel[1,1]
permanovas["LP Donación, Sexo_D, Edad_D, BMI_D",4] = permanova_taxa_corrected_donante_2_lp$tab_rel[2,1]

reactable::reactable(round(permanovas, 3)*100)
```

### Supervivencia

```{r}
# Ahora las covariables
covar_supervivencia_1_lp <- covar_lp %>%
    dplyr::select(Supervivencia)
```

```{r, eval=FALSE}
taxa_corrected_supervivencia_1_lp <- ConQuR(tax_tab=taxa_lp, batchid=batchid_lp, covariates=covar_supervivencia_1_lp, batch_ref="RUN 46", num_core = num_cores-2)

saveRDS(taxa_corrected_supervivencia_1_lp, "../RDSs/taxa_corrected_supervivencia_1_lp.RDS")
```

```{r}
taxa_corrected_supervivencia_1_lp <- readRDS("../RDSs/taxa_corrected_supervivencia_1_lp.RDS")

par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected_supervivencia_1_lp, factor=batchid_lp, main="ConQuR (Default), Bray-Curtis")

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected_supervivencia_1_lp, factor=batchid_lp, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")

```

```{r}
permanova_taxa_corrected_supervivencia_1_lp <- PERMANOVA_R2(TAX=taxa_corrected_supervivencia_1_lp, batchid=batchid_lp, covariates=covar_supervivencia_1_lp, key_index=1)

permanovas["Supervivencia (LP)",1] = permanova_taxa_corrected_supervivencia_1_lp$tab_count[1,1]
permanovas["Supervivencia (LP)",2] = permanova_taxa_corrected_supervivencia_1_lp$tab_count[2,1]
permanovas["Supervivencia (LP)",3] = permanova_taxa_corrected_supervivencia_1_lp$tab_rel[1,1]
permanovas["Supervivencia (LP)",4] = permanova_taxa_corrected_supervivencia_1_lp$tab_rel[2,1]

reactable::reactable(round(permanovas, 3)*100)
```

#### Supervivencia con datos donante

```{r}
# Ahora las covariables
covar_supervivencia_lp <- covar_lp %>%
    dplyr::select(Donación, Sexo_D, Edad_D, BMI_D, Supervivencia)
```

```{r, eval=FALSE}
taxa_corrected_supervivencia_lp <- ConQuR(tax_tab=taxa_lp, batchid=batchid_lp, covariates=covar_supervivencia_lp, batch_ref="RUN 46", num_core = num_cores-2)

saveRDS(taxa_corrected_supervivencia_lp, "../RDSs/taxa_corrected_supervivencia_lp.RDS")
```

```{r}
taxa_corrected_supervivencia_lp <- readRDS("../RDSs/taxa_corrected_supervivencia_lp.RDS")

par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected_supervivencia_lp, factor=batchid_lp, main="ConQuR (Default), Bray-Curtis")

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected_supervivencia_lp, factor=batchid_lp, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")

```

```{r}
permanova_taxa_corrected_supervivencia_lp <- PERMANOVA_R2(TAX=taxa_corrected_supervivencia_lp, batchid=batchid_lp, covariates=covar_supervivencia_lp, key_index=1)

permanovas["Supervivencia, Donación, Sexo_D, Edad_D, BMI_D (LP)",1] = permanova_taxa_corrected_supervivencia_lp$tab_count[1,1]
permanovas["Supervivencia, Donación, Sexo_D, Edad_D, BMI_D (LP)",2] = permanova_taxa_corrected_supervivencia_lp$tab_count[2,1]
permanovas["Supervivencia, Donación, Sexo_D, Edad_D, BMI_D (LP)",3] = permanova_taxa_corrected_supervivencia_lp$tab_rel[1,1]
permanovas["Supervivencia, Donación, Sexo_D, Edad_D, BMI_D (LP)",4] = permanova_taxa_corrected_supervivencia_lp$tab_rel[2,1]

reactable::reactable(round(permanovas, 3)*100)
```

### Variables de Salida MEAF_score, Supervivencia, AR, AHT, Biliary_complications

```{r}
# Ahora las covariables
covar_salida_lp <- covar_lp %>%
    dplyr::select(Supervivencia, MEAF_score, AR, AHT, Biliary_complications)
```

```{r, eval=FALSE}
taxa_corrected_salida_lp <- ConQuR(tax_tab=taxa_lp, batchid=batchid_lp, covariates=covar_salida_lp, batch_ref="RUN 2", num_core = num_cores-2)

saveRDS(taxa_corrected_salida_lp, "../RDSs/taxa_corrected_salida_lp.RDS")
```

```{r}
taxa_corrected_salida_lp <- readRDS("../RDSs/taxa_corrected_salida_lp.RDS")

par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected_salida_lp, factor=batchid_lp, main="ConQuR (Default), Bray-Curtis")

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected_salida_lp, factor=batchid_lp, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")

```

```{r}
permanova_taxa_corrected_salida_lp <- PERMANOVA_R2(TAX=taxa_corrected_salida_lp, batchid=batchid_lp, covariates=covar_salida_lp, key_index=1)

permanovas["Supervivencia, MEAF_score, AR, AHT, Biliary_complications (LP)",1] = permanova_taxa_corrected_salida_lp$tab_count[1,1]
permanovas["Supervivencia, MEAF_score, AR, AHT, Biliary_complications (LP)",2] = permanova_taxa_corrected_salida_lp$tab_count[2,1]
permanovas["Supervivencia, MEAF_score, AR, AHT, Biliary_complications (LP)",3] = permanova_taxa_corrected_salida_lp$tab_rel[1,1]
permanovas["Supervivencia, MEAF_score, AR, AHT, Biliary_complications (LP)",4] = permanova_taxa_corrected_salida_lp$tab_rel[2,1]

reactable::reactable(round(permanovas, 3)*100)
```

### Variables de Salida MEAF_score, Supervivencia, AR, AHT, Biliary_complications

```{r}
# Ahora las covariables
covar_salida_lp <- covar_lp %>%
    dplyr::select(Supervivencia, MEAF_score, AR, AHT, Biliary_complications)
```

```{r, eval=FALSE}
taxa_corrected_salida_lp <- ConQuR(tax_tab=taxa_lp, batchid=batchid_lp, covariates=covar_salida_lp, batch_ref="RUN 1", num_core = num_cores-2)

saveRDS(taxa_corrected_salida_lp, "../RDSs/taxa_corrected_salida_lp.RDS")
```

```{r}
taxa_corrected_salida_lp <- readRDS("../RDSs/taxa_corrected_salida_lp.RDS")

par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected_salida_lp, factor=batchid_lp, main="ConQuR (Default), Bray-Curtis")

Plot_PCoA(TAX=taxa_lp, factor=batchid_lp, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected_salida_lp, factor=batchid_lp, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")

```

```{r}
permanova_taxa_corrected_salida_lp <- PERMANOVA_R2(TAX=taxa_corrected_salida_lp, batchid=batchid_lp, covariates=covar_salida_lp, key_index=1)

permanovas["Supervivencia, MEAF_score, AR, AHT, Biliary_complications (LP)",1] = permanova_taxa_corrected_salida_lp$tab_count[1,1]
permanovas["Supervivencia, MEAF_score, AR, AHT, Biliary_complications (LP)",2] = permanova_taxa_corrected_salida_lp$tab_count[2,1]
permanovas["Supervivencia, MEAF_score, AR, AHT, Biliary_complications (LP)",3] = permanova_taxa_corrected_salida_lp$tab_rel[1,1]
permanovas["Supervivencia, MEAF_score, AR, AHT, Biliary_complications (LP)",4] = permanova_taxa_corrected_salida_lp$tab_rel[2,1]

reactable::reactable(round(permanovas, 3)*100)
```



# Fine tunning

## Lasso penalty

```{r, eval=FALSE}
options(warn=-1)
taxa_corrected2_lasso = ConQuR(tax_tab=taxa_lp, 
                         batchid=batchid_lp, 
                         covariates=covar_supervivencia_lp, 
                         batch_ref="PGM 135",
                         logistic_lasso=T, 
                         quantile_type="lasso", 
                         interplt=T,
                         lambda_quantile="2p/logn")

saveRDS(taxa_corrected2_lasso, "taxa_corrected2_lasso.RDS")
```

```{r}
taxa_corrected2_lasso <- readRDS("taxa_corrected2_lasso.RDS")
par(mfrow=c(2, 2))

Plot_PCoA(TAX=taxa, factor=batchid, main="Before Correction, Bray-Curtis")
Plot_PCoA(TAX=taxa_coregida_pgm135, factor=batchid, main="ConQuR (Default), Bray-Curtis")
Plot_PCoA(TAX=taxa_corrected2_lasso, factor=batchid, main="ConQuR (Lasso penalty), Bray-Curtis")

Plot_PCoA(TAX=taxa, factor=batchid, dissimilarity="Aitch", main="Before Correction, Aitchison")
Plot_PCoA(TAX=taxa_corrected2_lasso, factor=batchid, dissimilarity="Aitch", main="ConQuR (Default), Aitchison")
Plot_PCoA(TAX=taxa_coregida_pgm135, factor=batchid, dissimilarity="Aitch", main="ConQuR (Lasso penalty), Aitchison")

```

```{r}
permanova_taxa_corrected_donante_2 <- PERMANOVA_R2(TAX=taxa_corrected_donante_2, batchid=batchid, covariates=covar_donante_2, key_index=1)

permanovas["Donación, Sexo_D, Edad_D, BMI_D",1] = permanova_taxa_corrected_donante_2$tab_count[1,1]
permanovas["Donación, Sexo_D, Edad_D, BMI_D",2] = permanova_taxa_corrected_donante_2$tab_count[2,1]
permanovas["Donación, Sexo_D, Edad_D, BMI_D",3] = permanova_taxa_corrected_donante_2$tab_rel[1,1]
permanovas["Donación, Sexo_D, Edad_D, BMI_D",4] = permanova_taxa_corrected_donante_2$tab_rel[2,1]

reactable::reactable(round(permanovas, 3)*100)
```



## Automatica

```{r}
result_tuned <- Tune_ConQuR(tax_tab=taxa,
                           batchid=batchid,
                           covariates=covar_donante_2,
                           batch_ref_pool=c("RUN 46", "PGM 135"),
                           logistic_lasso_pool=c(T, F),
                           quantile_type_pool=c("standard", "lasso"),
                           simple_match_pool=c(T, F),
                           lambda_quantile_pool=c(NA, "2p/n", "2p/logn"),
                           interplt_pool=c(T, F),
                           frequencyL=0,
                           frequencyU=1,
                           num_core = num_cores-2)

```

