---
title: "Covariables limpieza"
author: "Fernando Lucas Ruiz (fernando.lucas@um.es)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    highlight: kate
    number_sections: true
    theme: spacelab
    toc: true
    toc_float: true
    code_folding: "hide"
  pdf_document:
    toc: true
subtitle: Cirugía digestiva, endocrina y trasplante de órganos abdominales (IMIB)
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r, message=FALSE}
otus_lp_t1_t3 <- readRDS("../RDSs/otus_lp_t1_t3.RDS")
otus_bilis <- readRDS("../RDSs/otus_bilis.RDS")
otus_negative_controls <- readRDS("../RDSs/otus_negative_controls.RDS")


source("Librerias.R")
```


# Lectura datos

```{r}
# Cogemos covariables
covs <- read_excel("../TABLA LIQUIDOS TH_microbiota.xlsx", sheet = 2)

# quitar muestra DAMPS-P39 porque no se analizó
covs <- covs %>% 
    dplyr::filter(nombre_muestra != "DAMPS-P39") %>%
    # Quitar muestra 18_Alb porque murió en quirófano
    dplyr::filter(nombre_muestra != "18_Alb")
```

```{r}
vis_miss(covs)
```

## Retirar variables

```{r}
covs <- covs %>%
    dplyr::select(-c("LÍQUIDO", "TEJIDO-T1", "TEJIDO-T3", "CÓDIGO", "Number")) %>%
    dplyr::select(-c("FWI")) %>% # lo quito porque soalmente lo podemos medir en los muertos DCD
    dplyr::select(-c("SHOCK", "Days_ex_rtx"))

```

```{r}
covs <- covs %>%
    dplyr::select(nombre_muestra, Donación, Sexo_D, Edad_D, BMI_D, GOT_D, GPT_D, PT_ACT_D, Cold_Isch,  MEAF_score, AR, AHT, Graft_disfunct, Biliary_complications, Supervivencia)
```


## Factorizar variables

```{r}
# cambiar 0s y 1s de Supervivencia

covs$Supervivencia <- ifelse(covs$Supervivencia == 0, 1, 0)
```


```{r}

covs$Donación <- factor(covs$Donación, levels = c(0, 1), labels = c("DBD", "DCD"))
# covs$Sub_Donac <- factor(covs$Sub_Donac, levels = c(0, 1, 2, 3, 4), labels = c("ACV", "TCE", "Encefalopatía anóxica", "Cardiomiopatía", "Otros"))
covs$Sexo_D <- factor(covs$Sexo_D, levels = c(0,1), labels = c("Masculino", "Femenino"))
# covs$TX_x_RTX <- factor(covs$TX_x_RTX, levels = c(0,1), labels = c("NO", "SI"))
# covs$Machine <- factor(covs$Machine, levels = c(0,1,2), labels = c("SRR","NRP", "DBD"))
# covs$NRP_Total <- factor(covs$NRP_Total, levels = c(0,1), labels = c("NO","SI"))
# covs$Sexo_R <- factor(covs$Sexo_R, levels = c(0,1), labels = c("Masculino", "Femenino"))
# covs$Disease_R <- factor(covs$Disease_R, 
#                          levels = c(0:20), c("CIRROSIS_ALCOHÓLICA", "HBV", "HCV",	"AUTOINMUNE", "NASH",	"HEMOCROMATOSIS", "ALFA1", "CIRROSIS_BILIAR_PRIMARIA",	"FIBROSIS_CONGÉNITA",	"WILSON", "CEP", "CIRROSIS_CRIPTOGÉNICA", "METASTASIS", "TROMBOSIS", "HTPSEC_BUDD_CHIARI", "POLIQUISTOSIS", "FALLO_HEPÁTICO_FULMINANTE", "COLANGIOPATÍA_ISQUÉMICA", "HEPATOPATIA_CRONICA", "HCC", "RECHAZO_TARDIO")
#                          )
# covs$CHIMERISM <- factor(covs$CHIMERISM, levels = c(0,1), labels = c("NO", "SI"))
# covs$Anastom <- factor(covs$Anastom, levels = c(0,1,3,4,5), labels = c("VB/VB", "CON KEHR", "Biodegradable", "Hepaticoyeyunostomía", "Otros"))
covs$AR <- factor(covs$AR, levels = c(0,1,2), labels = c("NO", "SI", "NO VALORABLE"))
covs$AHT <- factor(covs$AHT, levels = c(0,1,2), labels = c("NO", "SI", "NO VALORABLE"))
covs$Graft_disfunct <- factor(covs$Graft_disfunct, levels = c(0,1,2), labels = c("NO", "SI", "NO VALORABLE"))
covs$Biliary_complications <- factor(covs$Biliary_complications, levels = c(0,1,2), labels = c("NO", "SI", "NO VALORABLE"))
# covs$Exitus <- factor(covs$Exitus, levels = c(0,1,2), labels = c("SI", "NO", "NO VALORABLE"))
# covs$Need_RTX <- factor(covs$Need_RTX, levels = c(0,1,2), labels = c("NO", "SI", "NO VALORABLE"))
covs$Supervivencia <- factor(covs$Supervivencia, levels = c(0,1,2), labels = c("NO", "SI", "NO VALORABLE"))
```

```{r}
# Cambiar los "NO VALORABLES" por NAs
covs[covs == "NO VALORABLE"] <- NA

covs$AR <- factor(covs$AR, levels = c("NO", "SI"))
covs$AHT <- factor(covs$AHT, levels = c("NO", "SI"))
covs$Graft_disfunct <- factor(covs$Graft_disfunct, levels = c("NO", "SI"))
covs$Biliary_complications <- factor(covs$Biliary_complications, levels = c("NO", "SI"))
# covs$Exitus <- factor(covs$Exitus, levels = c("SI", "NO"))
# covs$Need_RTX <- factor(covs$Need_RTX, levels =  c("NO", "SI"))
covs$Supervivencia <- factor(covs$Supervivencia, levels = c("SI", "NO"))
```

```{r}
vis_miss(covs)
```

## Imputar datos

```{r, eval=FALSE}
set.seed(1234)
covs <- complete(mice(covs, method = "rf", m = 5, maxit = 50))

saveRDS(covs, "../RDSs/covs.RDS")
```

```{r}
covs <- readRDS("../RDSs/covs.RDS")
```


# Análizar variables

```{r, fig.height=20, fig.width=10}
factor_cols <- sapply(covs, is.factor)
data_long <- pivot_longer(covs, cols = names(which(factor_cols)), 
                          names_to = "Variable", values_to = "Value")

plots <- list()

for(variable in unique(data_long$Variable)) {
  
  data_filtered <- data_long %>%
    dplyr::filter(Variable == variable) %>%
    dplyr::group_by(Value) %>%
    dplyr::summarize(Frequency = n(), .groups = 'drop') %>%
    mutate(Percentage = Frequency / sum(Frequency) * 100) %>%
    ungroup()
  
  p <- ggplot(data_filtered, aes(x = Value, y = Percentage, fill = Value)) +
    geom_col(position = position_dodge(), alpha = 0.7) +
    scale_fill_viridis_d() +
    theme_minimal() +
    labs(title = variable,
         x = "", y = "Percentage") +
    theme(legend.position = "none") +
    theme(plot.title = element_text(size = 12), 
        axis.title = element_text(size = 10),
        axis.text.x = element_text(angle = 45, hjust = 1))
  
  plots[[variable]] <- p
}

do.call(grid.arrange, c(plots, ncol = 3))
```

```{r, fig.height=10, fig.width=10}
plots <- list()
for (colname in names(covs)) {
    if (!is.factor(covs[[colname]]) & !is.character(covs[[colname]])) {
        p <- ggplot(covs, aes_string(x = colname)) +
            #geom_density(adjust=1.5, alpha=.7, fill="#f1e6b2") +
            geom_density(adjust=1.5, fill="#f1e6b2", alpha = 0.7) +
            theme_minimal() +
            labs(title = colname,
                x = colname) 

        plots[[colname]] <- p
    }
}

do.call(grid.arrange, c(plots, ncol= 2))
```

```{r, fig.height=10, fig.width=8}
plots <- list()
for (colname in names(covs)) {
    if (!is.factor(covs[[colname]]) & !is.character(covs[[colname]])) {
        p <- ggplot(covs, aes_string(y = colname, x = "Supervivencia", color = "Supervivencia")) +
            #geom_density(adjust=1.5, alpha=.7, fill="#f1e6b2") +
            geom_boxplot(adjust=1.5, fill="#f1e6b2", alpha = 0.7) +
            geom_jitter(size = 0.5, alpha = 0.5, aes_string(y = colname, x = "Supervivencia")) +
            theme_minimal() +
            stat_compare_means(vjust =2 ) +
            labs(title = colname,
                x = colname) 

        plots[[colname]] <- p
    }
}

do.call(grid.arrange, c(plots, ncol= 2))
```

## One-hot encoding

```{r}
covs2 <- data.frame(matrix(ncol = 0, nrow = nrow(covs))) # Hago un dataframe vacio para meter los datos procesados

for (colname in names(covs)) {
  if (is.factor(covs[[colname]]) & length(levels(covs[[colname]])) > 2) {

    dummy_df <- dummy_cols(covs[colname], 
                           remove_selected_columns = TRUE) # quitar las variables iniciales
    
    dummy_df <- data.frame(lapply(dummy_df, factor))

    covs2 <- cbind(covs2, dummy_df)

  } else {

    covs2[[colname]] <- covs[[colname]] # si son numéricas o categóricas binarias, las añadimos igual
  }
}
covs <- covs2
covs
```

```{r}
# vamos a quitar aquellas columnas que solamente tengan 0s
lista <- list()
for (i in names(covs)){
    if(all(covs[[i]] == 0)) {
       lista <- append(lista, i)
    } 
}
covs <- covs[, !names(covs) %in% lista]
```

## Estadistico entre Supervivencia vs No supervivencia de cada variable

```{r}
covs_statistics <- data.frame()
for (i in names(covs)){
    
    if (is.numeric(covs[[i]])){
        datos <- covs %>%
            dplyr::group_by(Supervivencia) %>%
            dplyr::summarize(mediana = median(.data[[i]], na.rm = TRUE),
                      sd_value = sd(.data[[i]], na.rm = TRUE)) 
        
        wilcox_test_result <- wilcox.test(covs[[i]] ~ covs$Supervivencia)
        
        covs_statistics[i, "Rechazo"] <- paste0(datos[1,2], " (", round(datos[1,3], 2), ")")
        covs_statistics[i, "Supervivencia"] <- paste0(datos[2,2], " (", round(datos[2,3], 2), ")")
        covs_statistics[i, "p-value"] <- if (wilcox_test_result$p.value > 0.05){
            "n.s."
        } else if (wilcox_test_result$p.value < 0.05 & wilcox_test_result$p.value > 0.01){
            "<0.05"
        } else if (wilcox_test_result$p.value < 0.01 & wilcox_test_result$p.value > 0.001){
            "<0.01"
        } else if (wilcox_test_result$p.value < 0.001) {
            "<0.001"
        }

    } else if (is.factor(covs[[i]])){
        if (i == "Supervivencia") {
            next
        }
        
        frecuencia <- table(covs[[i]], covs[["Supervivencia"]])
        rownames(frecuencia) <- c(paste(i, rownames(frecuencia), sep = "_"))
        colnames(frecuencia) <- c("Rechazo", "Supervivencia")
        
        test <- fisher.test(frecuencia)
        
        covs_statistics[i, "Rechazo"] <- paste0(frecuencia[2,1], "/", frecuencia[2,1] + frecuencia[1,1]," (", round(frecuencia[2,1]/(frecuencia[2,1] + frecuencia[1,1])*100, 2), "%)")
        covs_statistics[i, "Supervivencia"] <- paste0(frecuencia[2,2], "/", frecuencia[2,2] + frecuencia[1,2]," (", round(frecuencia[2,2]/(frecuencia[2,2] + frecuencia[1,2])*100, 2), "%)")
        covs_statistics[i, "p-value"] <- if (test$p.value > 0.05){
            "n.s."
        } else if (test$p.value < 0.05 & test$p.value > 0.01){
            "<0.05"
        } else if (test$p.value < 0.01 & test$p.value > 0.001){
            "<0.01"
        } else if (test$p.value < 0.001) {
            "<0.001"
        }
        
    }
}

DT::datatable(covs_statistics)
```

## Representación en función de Supervivencia

```{r, fig.width=15, fig.height=10}
data_long <- covs %>%
  dplyr::select(-nombre_muestra, -Edad_D, -BMI_D, -GOT_D, -GPT_D, -PT_ACT_D, -Cold_Isch, -MEAF_score) %>%
  pivot_longer(cols = -Supervivencia, 
               names_to = "Variable", values_to = "Value")

plots <- list()

for(variable in unique(data_long$Variable)) {
  data_long$Supervivencia <- factor(data_long$Supervivencia)
  
  data_filtered <- data_long %>%
    dplyr::filter(Variable == variable) %>%
    dplyr::group_by(Value, Supervivencia) %>%
    dplyr::summarize(Frequency = n(), .groups = 'drop') %>%
    mutate(Percentage = Frequency / sum(Frequency) * 100) %>%
    ungroup()
  
  p <- ggplot(data_filtered, aes(x = Supervivencia, y = Percentage, fill = Value)) +
    geom_col(position = "stack", alpha = 0.7) +
    scale_fill_viridis_d() +
    theme_minimal() +
    labs(title = variable,
         x = "", y = "Percentage") +
    theme(legend.position = "none") +
    theme(plot.title = element_text(size = 16), axis.title = element_text(size = 10)) +
    theme(axis.text.x = element_text(size = 16))+ 
    theme(legend.position = "top", legend.title = element_blank())
  
  plots[[variable]] <- p
}

do.call(grid.arrange, c(plots, ncol=4))
```

```{r, fig.width=15, fig.height=10}
data_long <- covs %>%
  dplyr::select(-nombre_muestra, -Edad_D, -BMI_D, -GOT_D, -GPT_D, -PT_ACT_D, -Cold_Isch, -MEAF_score) %>%
  pivot_longer(cols = -Supervivencia, 
               names_to = "Variable", values_to = "Value")

plots <- list()

for(variable in unique(data_long$Variable)) {
  data_long$Supervivencia <- factor(data_long$Supervivencia)
  
  data_filtered <- data_long %>%
    dplyr::filter(Variable == variable) %>%
    dplyr::group_by(Value, Supervivencia) %>%
    dplyr::summarize(Frequency = n(), .groups = 'drop') %>%
    mutate(Percentage = Frequency / sum(Frequency) * 100) %>%
    ungroup()
  
  p <- ggplot(data_filtered, aes(x = Supervivencia, y = Percentage, fill = Value)) +
    geom_col(position = "fill", alpha = 0.7) +
    scale_fill_viridis_d() +
    theme_minimal() +
    labs(title = variable,
         x = "", y = "Percentage") +
    theme(legend.position = "none") +
    theme(plot.title = element_text(size = 16), axis.title = element_text(size = 10)) +
    theme(axis.text.x = element_text(size = 16))+ 
    theme(legend.position = "top", legend.title = element_blank())
  
  plots[[variable]] <- p
}

do.call(grid.arrange, c(plots, ncol=4))
```

```{r, fig.width=10, fig.height=10}
data <- covs %>%
  dplyr::select(Edad_D, BMI_D, GOT_D, GPT_D, PT_ACT_D, Cold_Isch, MEAF_score, Supervivencia)

plots <- list()

for(variable in names(data)) {
    if (variable == "Supervivencia"){
        next
    }
  p <- ggplot(data, aes_string(y = variable, x = "Supervivencia", fill = "Supervivencia")) +
    geom_boxplot(alpha=0.4) +
    geom_jitter(color ="#8B1A1A", size = 1, alpha = 0.7, width = 0.15) +
    scale_fill_viridis_d()+
    theme_minimal() +
    labs(title = variable,
         x = "", y = "Percentage") +
    theme(legend.position = "none") +
      stat_compare_means(label = "p.signif", vjust = 2, hjust= 2) +
    theme(plot.title = element_text(size = 16), axis.title = element_text(size = 10)) +
    theme(axis.text.x = element_text(size = 16)) 
  
  plots[[variable]] <- p
}

do.call(grid.arrange, c(plots, ncol=3))
```

# Variables por batches

```{r}
samples <- otus_lp_t1_t3 %>%
    dplyr::select(codigo, nombre_muestra, tipo_muestra, Batch) %>%
    as.data.frame()

samples <- samples[!duplicated(samples$codigo), ]

samples_metadata <- dplyr::left_join(samples, covs, by= "nombre_muestra" )
```

```{r}
samples_lp <- samples_metadata %>%
    dplyr::filter(tipo_muestra == "LP")

samples_t1 <- samples_metadata %>%
    dplyr::filter(tipo_muestra == "T1")

samples_t3 <- samples_metadata %>%
    dplyr::filter(tipo_muestra == "T3")
```

```{r, fig.width=15, fig.height=15}
data_long <- samples_lp %>%
  dplyr::select(-nombre_muestra, -codigo,-tipo_muestra, -Edad_D, -BMI_D, -GOT_D, -GPT_D, -PT_ACT_D, -Cold_Isch, -MEAF_score) %>%
  pivot_longer(cols = -Batch, 
               names_to = "Variable", values_to = "Value")

plots <- list()

for(variable in unique(data_long$Variable)) {
  data_long$Batch <- factor(data_long$Batch)
  
  data_filtered <- data_long %>%
    dplyr::filter(Variable == variable) %>%
    dplyr::group_by(Value, Batch) %>%
    dplyr::summarize(Frequency = n(), .groups = 'drop') %>%
    mutate(Percentage = Frequency / sum(Frequency) * 100) %>%
    ungroup()
  
  p <- ggplot(data_filtered, aes(x = Batch, y = Percentage, fill = Value)) +
    geom_col(position = "fill", alpha = 0.7) +
    scale_fill_viridis_d() +
    theme_minimal() +
    labs(title = variable,
         x = "", y = "Percentage") +
    theme(legend.position = "none") +
    theme(plot.title = element_text(size = 16), axis.title = element_text(size = 10)) +
    theme(axis.text.x = element_text(size = 16, angle = 45))+ 
    theme(legend.position = "top", legend.title = element_blank())
  
  plots[[variable]] <- p
}

do.call(grid.arrange, c(plots, ncol=4))
```

```{r, fig.width=10, fig.height=10}
data <- samples_lp %>%
  dplyr::select(Edad_D, BMI_D, GOT_D, GPT_D, PT_ACT_D, Cold_Isch,MEAF_score, Supervivencia, Batch)

plots <- list()

for(variable in names(data)) {
    if (variable == "Supervivencia"){
        next
    }
  p <- ggplot(data, aes_string(y = variable, x = "Batch", fill = "Batch")) +
    geom_boxplot(alpha=0.4) +
    geom_jitter(color ="#8B1A1A", size = 1, alpha = 0.7, width = 0.15) +
    scale_fill_viridis_d()+
    theme_minimal() +
    labs(title = variable,
         x = "", y = "Units") +
    theme(legend.position = "none") +
      stat_compare_means() + 
    theme(plot.title = element_text(size = 16), axis.title = element_text(size = 10)) +
    theme(axis.text.x = element_text(size = 12, angle = 45))
  
  plots[[variable]] <- p
}

do.call(grid.arrange, c(plots, ncol=3))
```

# Correlaciones

```{r, fig.width=10, fig.height=10}
library(Hmisc)  # Para correlaciones numéricas
library(polycor)  # Para correlaciones policóricas (ordinales)
library(vcd)  # Para Cramér's V

# 1. Correlaciones entre variables numéricas
numeric_vars <- covs[, sapply(covs, is.numeric)]
correlation_numeric <- rcorr(as.matrix(numeric_vars), type = "spearman")
correlation_matrix <- correlation_numeric$r  # Matriz de correlaciones
pvalue_matrix <- correlation_numeric$P  # Matriz de p-valores

# 2. Cramér's V para variables categóricas
cat_vars <- covs[, sapply(covs, is.factor)]
cramer_v_results <- matrix(NA, ncol = ncol(cat_vars), nrow = ncol(cat_vars),
                           dimnames = list(names(cat_vars), names(cat_vars)))
pvalue_cramer <- matrix(NA, ncol = ncol(cat_vars), nrow = ncol(cat_vars),
                        dimnames = list(names(cat_vars), names(cat_vars)))

for (i in 1:ncol(cat_vars)) {
  for (j in 1:ncol(cat_vars)) {
    if (i != j) {
      test_result <- assocstats(table(cat_vars[, i], cat_vars[, j]))
      cramer_v_results[i, j] <- test_result$cramer
      pvalue_cramer[i, j] <- chisq.test(table(cat_vars[, i], cat_vars[, j]), correct = T)$p.value
    } else {
      cramer_v_results[i, j] <- 1  # Correlación perfecta consigo mismo
      pvalue_cramer[i, j] <- NA  # No tiene sentido un p-valor
    }
  }
}

# 3. Correlaciones entre variables numéricas y categóricas (binarias)
point_biserial_results <- matrix(NA, ncol = ncol(cat_vars), nrow = ncol(numeric_vars),
                                 dimnames = list(names(numeric_vars), names(cat_vars)))
pvalue_point_biserial <- matrix(NA, ncol = ncol(cat_vars), nrow = ncol(numeric_vars),
                                dimnames = list(names(numeric_vars), names(cat_vars)))

for (cat_var in names(cat_vars)) {
  for (num_var in names(numeric_vars)) {
    test_result <- cor.test(numeric_vars[[num_var]], as.numeric(cat_vars[[cat_var]]), method = "pearson")
    point_biserial_results[num_var, cat_var] <- test_result$estimate
    pvalue_point_biserial[num_var, cat_var] <- test_result$p.value
  }
}

# Resultados:
# - correlation_matrix y pvalue_matrix para correlaciones entre numéricas.
# - cramer_v_results y pvalue_cramer para relaciones entre categóricas.
# - point_biserial_results y pvalue_point_biserial para relaciones entre numéricas y categóricas binarias.

correlation_df <- as.data.frame(correlation_matrix)
pvalue_df <- as.data.frame(pvalue_matrix)
cramer_v_df <- as.data.frame(cramer_v_results)
pvalue_cramer_df <- as.data.frame(pvalue_cramer)
point_biserial_df <- as.data.frame(point_biserial_results)
pvalue_point_biserial_df <- as.data.frame(pvalue_point_biserial)

# Obtener todos los nombres de variables para crear una matriz completa
all_var_names <- unique(c(
  rownames(correlation_df), colnames(correlation_df),
  rownames(cramer_v_df), colnames(cramer_v_df),
  rownames(point_biserial_df), colnames(point_biserial_df)
))

# Crear data frames vacíos con todas las posibles combinaciones de nombres
empty_df <- as.data.frame(matrix(NA, nrow = length(all_var_names), ncol = length(all_var_names),
                                 dimnames = list(all_var_names, all_var_names)))

# Combinar todas las matrices de coeficientes en un solo data frame
correlation_combined <- empty_df
correlation_combined[rownames(cramer_v_df), colnames(cramer_v_df)] <- cramer_v_df
correlation_combined[rownames(point_biserial_df), colnames(point_biserial_df)] <- point_biserial_df
correlation_combined[colnames(point_biserial_df), rownames(point_biserial_df)] <- data.frame (t(point_biserial_df))
correlation_combined[rownames(correlation_df), colnames(correlation_df)] <- correlation_df


# Combinar todas las matrices de coeficientes en un solo data frame
pvalue_combined <- empty_df
pvalue_combined[rownames(pvalue_cramer_df), colnames(pvalue_cramer_df)] <- pvalue_cramer_df
pvalue_combined[rownames(pvalue_point_biserial_df), colnames(pvalue_point_biserial_df)] <- pvalue_point_biserial_df
pvalue_combined[colnames(pvalue_point_biserial_df), rownames(pvalue_point_biserial_df)] <- data.frame (t(pvalue_point_biserial_df))
pvalue_combined[rownames(pvalue_df), colnames(pvalue_df)] <- pvalue_df

pvalue_combined[is.na(pvalue_combined)] <- 1


corrplot(as.matrix(correlation_combined), is.corr = T,
         method = "ellipse", 
         p.mat = as.matrix(pvalue_combined),
         sig.level = c(0.001, 0.01, 0.05),
         insig = "label_sig",
         pch.cex = 1,
         col = paletteer_c("grDevices::Blue-Red 3", 30),
         tl.col = "black",
         tl.srt = 45,
         tl.offset = 1,
         # cl.pos = 'b',
         cl.length = 5,
         cl.ratio = 0.1,
         type = 'lower'

         #addCoef.col = 'black'
         ) %>%
    corrRect(name = c('Sexo_D', 'Supervivencia'))
```


# Guardar datos

```{r}
saveRDS(covs, "../RDSs/covs.RDS")
```





